// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/yloveya1/metricsalert/internal/model"
)

// MockIRuntimeAgent is a mock of IRuntimeAgent interface.
type MockIRuntimeAgent struct {
	ctrl     *gomock.Controller
	recorder *MockIRuntimeAgentMockRecorder
}

// MockIRuntimeAgentMockRecorder is the mock recorder for MockIRuntimeAgent.
type MockIRuntimeAgentMockRecorder struct {
	mock *MockIRuntimeAgent
}

// NewMockIRuntimeAgent creates a new mock instance.
func NewMockIRuntimeAgent(ctrl *gomock.Controller) *MockIRuntimeAgent {
	mock := &MockIRuntimeAgent{ctrl: ctrl}
	mock.recorder = &MockIRuntimeAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRuntimeAgent) EXPECT() *MockIRuntimeAgentMockRecorder {
	return m.recorder
}

// GetMetrics mocks base method.
func (m *MockIRuntimeAgent) GetMetrics() []*models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].([]*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockIRuntimeAgentMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockIRuntimeAgent)(nil).GetMetrics))
}
