// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRuntimeAgent is a mock of IRuntimeAgent interface.
type MockIRuntimeAgent struct {
	ctrl     *gomock.Controller
	recorder *MockIRuntimeAgentMockRecorder
}

// MockIRuntimeAgentMockRecorder is the mock recorder for MockIRuntimeAgent.
type MockIRuntimeAgentMockRecorder struct {
	mock *MockIRuntimeAgent
}

// NewMockIRuntimeAgent creates a new mock instance.
func NewMockIRuntimeAgent(ctrl *gomock.Controller) *MockIRuntimeAgent {
	mock := &MockIRuntimeAgent{ctrl: ctrl}
	mock.recorder = &MockIRuntimeAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRuntimeAgent) EXPECT() *MockIRuntimeAgentMockRecorder {
	return m.recorder
}

// GetCounterMetrics mocks base method.
func (m *MockIRuntimeAgent) GetCounterMetrics() map[string]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterMetrics")
	ret0, _ := ret[0].(map[string]int64)
	return ret0
}

// GetCounterMetrics indicates an expected call of GetCounterMetrics.
func (mr *MockIRuntimeAgentMockRecorder) GetCounterMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterMetrics", reflect.TypeOf((*MockIRuntimeAgent)(nil).GetCounterMetrics))
}

// GetGaugeMetrics mocks base method.
func (m *MockIRuntimeAgent) GetGaugeMetrics() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeMetrics")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetGaugeMetrics indicates an expected call of GetGaugeMetrics.
func (mr *MockIRuntimeAgentMockRecorder) GetGaugeMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeMetrics", reflect.TypeOf((*MockIRuntimeAgent)(nil).GetGaugeMetrics))
}
