// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/yloveya1/metricsalert/internal/model"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// SendMetric mocks base method.
func (m *MockIClient) SendMetric(metric *models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetric", metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMetric indicates an expected call of SendMetric.
func (mr *MockIClientMockRecorder) SendMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetric", reflect.TypeOf((*MockIClient)(nil).SendMetric), metric)
}

// SendMetricList mocks base method.
func (m *MockIClient) SendMetricList(metric []*models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetricList", metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMetricList indicates an expected call of SendMetricList.
func (mr *MockIClientMockRecorder) SendMetricList(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetricList", reflect.TypeOf((*MockIClient)(nil).SendMetricList), metric)
}
